### PR TITLE
docker: Update cachalot to v5

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
I think this is probably the 7th time I will ask for this, but should we release v6.0.s7 final? (we are at -rc6, but most rc were just updating infra stuff).

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Comment by gavin-norman-sociomantic** [comment]
>I think this is probably the 7th time I will ask for this, but should we release v6.0.s7 final? (we are at -rc6, but most rc were just updating infra stuff).

Would make sense.

**Comment by nemanja-boric-sociomantic** [comment]
Yes, now with the cachalot and the pinned versions inside docker images it's much easier to release final version of library like this - the user might not see any difference, but the code might be very broken, and it could manifest in a weird way. Previously, if I would tag the final version that would mean that _everybody_ gets an update which they might not be aware of or that they can't control. However, now, they know it's the part of the cachalot update so it's controllable and testable.

I'll do the release then.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, I'll release the final version then.

**Comment by leandro-lucarella-sociomantic** [comment]
https://travis-ci.org/sociomantic-tsunami/ebtree/builds/394495956

**Pull request merged**
