### PR TITLE
Add epoch for new packages.

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
This starts the new dpkg's epoch for the new packages, so the ordering
can be preserved for the new versions using `.sX` scheme.

### CODE REVIEW

**Review by leandro-lucarella-sociomantic — APPROVED** [review]

**Comment by nemanja-boric-sociomantic** [comment]
This doesn't seems to be working. The package is created and pushed to the `prerelease` channel, but `apt-cache policy` doesn't show package as available:

https://travis-ci.org/sociomantic-tsunami/ebtree/jobs/307923578#L629

```
(done `apt-get update`)
nemanjaboric@labs-129:/home/nemanjaboric/work/ebtree  git:(sociomantic*) $ apt-cache policy libebtree6
libebtree6:
  Installed: 6.0.socio6-xenial
  Candidate: 6.0.socio6-xenial
  Version table:
     6.0.socio7-rc4-xenial -50
        -50 https://dl.bintray.com/sociomantic-tsunami/dlang xenial/prerelease amd64 Packages
 *** 6.0.socio6-xenial 900
        900 https://ci.sociomantic.com/ubuntu/stable xenial/main amd64 Packages
        -25 https://ci.sociomantic.com/ubuntu/servers xenial/main amd64 Packages
        900 https://dl.bintray.com/sociomantic-tsunami/dlang xenial/release amd64 Packages
        100 /var/lib/dpkg/status
     6.0.socio5-xenial 900
        900 https://ci.sociomantic.com/ubuntu/stable xenial/main amd64 Packages
     6.0.s7-rc5-xenial -50
        -50 https://dl.bintray.com/sociomantic-tsunami/dlang xenial/prerelease amd64 Packages
```

As you can see, no `6.0.s7-rc6-xenial` package is available.

**Comment by nemanja-boric-sociomantic** [comment]
It is, however, available on the bintray:

https://bintray.com/sociomantic-tsunami/dlang/ebtree/v6.0.s7-rc6

**Comment by nemanja-boric-sociomantic** [comment]
Looks like the version information extraction didn't work as planned - the package got renamed to `libebtree1`:

```
nemanjaboric@labs-129:/home/nemanjaboric/work/ebtree  git:(sociomantic*) $ apt-cache policy libebtree1 
libebtree1:
  Installed: (none)
  Candidate: (none)
  Version table:
     1:6.0.s7-rc6-xenial -50
        -50 https://dl.bintray.com/sociomantic-tsunami/dlang xenial/prerelease amd64 Packages
```

**Comment by leandro-lucarella-sociomantic** [comment]
I have the feeling there is something wrong with fpm, probably there is a flag for epoch, the epoch is in the file name and I have the feeling it shouldn't

**Comment by leandro-lucarella-sociomantic** [comment]
`--epoch EPOCH`

**Comment by leandro-lucarella-sociomantic** [comment]
Try with that, and we should probably remove the broken package...

**Comment by leandro-lucarella-sociomantic** [comment]
I don't know where the `1` came in the package name, maybe a beaver bug because it doesn't expect the epoch?

**Comment by nemanja-boric-sociomantic** [comment]
OK, trying with `epoch` I got the file:

`libebtree6-dev_6.0.s7-rc6~dirty.20171127154751-xenial_amd64.deb`

which is good, and the version is:

```
nemanjaboric@labs-129:/home/nemanjaboric/work/ebtree  git:(epoch2*) $ dpkg -I deb/libebtree6-dev_6.0.s7-rc6~dirty.20171127154751-xenial_amd64.deb
 new debian package, version 2.0.
 size 55732 bytes: control archive=831 bytes.
     428 bytes,    12 lines      control              
     831 bytes,    13 lines      md5sums              
 Package: libebtree6-dev
 Version: 1:6.0.s7-rc6~dirty.20171127154751-xenial
```

So, this looks promising, let's see.

**Pull request merged**
